name: ear
channels:
  - defaults
dependencies:
  - pip=22.1.2
  - python=3.9.12
  - pip:
      - matplotlib==3.5.2
      - pandas==1.4.3
      - scikit-learn==1.1.1
      - scipy==1.8.1
      - numpy==1.23.0
      - pyyaml
      - tqdm
      - timm
      - tensorboard
      - albumentations
      - tensorflow
